// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWkQb9-diu27slWSUIsIhZ0Z3dqNbQnFU',
    appId: '1:426409977015:web:99848e1667fdc0c003d932',
    messagingSenderId: '426409977015',
    projectId: 'darcomapp-97370',
    authDomain: 'darcomapp-97370.firebaseapp.com',
    storageBucket: 'darcomapp-97370.firebasestorage.app',
    measurementId: 'G-X4JJ103Q53',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrCbtNSOWLOHctQamzyV-bc-NmotRVJ6Y',
    appId: '1:426409977015:android:0b87f46b9004151503d932',
    messagingSenderId: '426409977015',
    projectId: 'darcomapp-97370',
    storageBucket: 'darcomapp-97370.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD__w5_X_NuEb79_qHI7_y2mIdss3WzQRs',
    appId: '1:426409977015:ios:d2ad2207a65bd13203d932',
    messagingSenderId: '426409977015',
    projectId: 'darcomapp-97370',
    storageBucket: 'darcomapp-97370.firebasestorage.app',
    iosBundleId: 'com.example.darcomApp',
  );
}
